### PR TITLE
update pre-commit

### PR DESCRIPTION
**Pull request by lorenzwalthert**

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
@pat-s another passing pre-commit.ci run 😀

**Comment by lorenzwalthert** [comment]
> automatic updates: pre-commit.ci will periodically autoupdate your configuration ensuring that your hook versions are kept up to date. this autoupdate is currently scheduled weekly at approximately 18:00 UTC Monday.

**Comment by pat-s** [comment]
> @pat-s another passing pre-commit.ci run 😀. Also, for all other repos from mlr that have a .pre-commit-config.yaml like mlr-org/mlr3proba, a newer version is rquired in that file, i.e. rev: v0.1.3.9014 won't use {renv} and hence fail. Not sure if now pre-commit.ci will autoupdate the repos. This usually happens on monday, so lets just wait and see if it bumps rev.

Good to know, thanks!

I think I also need to update all repos with the `additional_dependencies` fields introduced in `precommit` 0.2.0 then to continue to work, correct?

**Comment by lorenzwalthert** [comment]
True.

**Pull request merged**
